name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Add permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build_with_gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-AdvancedTrainDetector
          path: ./build/libs/*
          retention-days: 30

      - name: Upload artifacts to the outside server
        if: steps.build_with_gradle.outcome == 'success' && contains(github.ref, github.event.repository.default_branch)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt -y install gridsite-clients
          for file in ./build/libs/*
          do
          curl -T "$file" -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" https://kotatsu.siro256.dev/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/$(urlencode $(echo $file | sed -r 's/^.*\/(.*)$/\1/')) --globoff
          done